# Generated by Django 6.0.4 on 2026-04-27 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
                ('course_type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], max_length=50)),
                ('textbooks', models.TextField(blank=True, help_text='List primary textbooks')),
                ('reference_books', models.TextField(blank=True, help_text='List reference materials')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FACULTY_APPROVED', '✅ Faculty Approved'), ('BOS_APPROVED', '✅ BOS Approved'), ('HOD_APPROVED', '✅ HOD Approved'), ('REJECTED', '❌ Rejected / Revision Required')], default='DRAFT', max_length=20)),
                ('copo_matrix', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Module Title')),
                ('teaching_hours', models.IntegerField(default=0)),
                ('course_objectives', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, verbose_name='Content & Details')),
                ('hands_on', models.TextField(blank=True, verbose_name='Hands-on / Self-Learning')),
                ('rbt_levels', models.CharField(blank=True, help_text='e.g., L1, L2, L3', max_length=100)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='syllabus.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='syllabus.syllabus')),
            ],
        ),
    ]
