# Generated by Django 6.0.4 on 2026-04-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='cie_marks',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='exam_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='lec_hours',
            field=models.IntegerField(default=3, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='objectives',
            field=models.TextField(blank=True, verbose_name='Course Objectives'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='other_hours',
            field=models.CharField(default='@', max_length=5, verbose_name='O'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='prac_hours',
            field=models.IntegerField(default=0, verbose_name='P'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='see_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], default='Theory', max_length=20),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='semester',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], default='VI', max_length=5),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='teaching_learning',
            field=models.TextField(blank=True, verbose_name='Teaching-Learning Process'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='total_hours',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='tut_hours',
            field=models.IntegerField(default=0, verbose_name='T'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_type',
            field=models.CharField(choices=[('PCC', 'PCC'), ('IPCC', 'IPCC'), ('PCCL', 'PCCL'), ('PEC', 'PEC'), ('OEC', 'OEC'), ('ETC', 'ETC'), ('AEC', 'AEC'), ('PRJ', 'PRJ'), ('HSMC', 'HSMC'), ('NCMC', 'NCMC')], default='ETC', max_length=10),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='credits',
            field=models.IntegerField(default=3),
        ),
    ]
