# Generated by Django 6.0.4 on 2026-04-28 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_module_is_deleted_syllabus_cie_marks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['module_number', 'id']},
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='reference_books',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='textbooks',
        ),
        migrations.AddField(
            model_name='module',
            name='has_hands_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='module_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='self_learning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='tb_chapter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='tb_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='module',
            name='tb_section',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='content_type',
            field=models.CharField(choices=[('theory_only', 'Only Theory'), ('theory_with_lab', 'Theory with Lab'), ('lab_only', 'Only Lab')], default='theory_only', max_length=20),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='lab_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='lab_prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='lab_self_learning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='reference_books_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='textbooks_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='hands_on',
            field=models.TextField(blank=True),
        ),
        migrations.RunSQL("UPDATE syllabus_module SET rbt_levels = '[]'", migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='module',
            name='rbt_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='lec_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='other_hours',
            field=models.CharField(default='@', max_length=5),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='prac_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='teaching_learning',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='tut_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LabExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('is_additional', models.BooleanField(default=False)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_experiments', to='syllabus.syllabus')),
            ],
            options={
                'ordering': ['is_additional', 'sl_no'],
            },
        ),
    ]
