# Generated by Django 6.0.4 on 2026-04-28 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_alter_module_options_remove_syllabus_reference_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='co_description',
            field=models.TextField(blank=True, default='After going through this course, the student will be able to'),
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_outcomes', to='syllabus.syllabus')),
            ],
            options={
                'ordering': ['sl_no'],
            },
        ),
    ]
