# Generated by Django 6.0.4 on 2026-04-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_syllabus_co_description_courseoutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='assessment_cie',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='assessment_general_rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='assessment_see',
            field=models.TextField(blank=True),
        ),
    ]
