# Generated by Django 6.0.4 on 2026-04-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_syllabus_assessment_cie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='activity_based_learning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='weblinks_custom',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='weblinks_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
