# Generated by Django 6.0.4 on 2026-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_syllabus_activity_based_learning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='cie_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='co_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_type',
            field=models.CharField(choices=[('PCC', 'PCC'), ('IPCC', 'IPCC'), ('PCCL', 'PCCL'), ('PEC', 'PEC'), ('OEC', 'OEC'), ('ETC', 'ETC'), ('AEC', 'AEC'), ('PRJ', 'PRJ'), ('HSMC', 'HSMC'), ('NCMC', 'NCMC')], default='PCC', max_length=10),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='exam_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='lec_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='other_hours',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='semester',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], default='I', max_length=5),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
