# Generated by Django 6.0.4 on 2026-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_alter_syllabus_cie_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='latest_remark',
            field=models.TextField(blank=True, help_text='Reason for rejection or approval comments.'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HOD', '⏳ Pending HOD Approval'), ('PENDING_ADMIN', '⏳ Pending Admin Approval'), ('APPROVED', '✅ Go ahead with implementation'), ('REJECTED_BY_HOD', '❌ Rejected by HOD'), ('REJECTED_BY_ADMIN', '❌ Rejected by Admin')], default='DRAFT', max_length=20),
        ),
    ]
