# Generated by Django 6.0.4 on 2026-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0008_syllabus_latest_remark_alter_syllabus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='lab_slots',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
