# Generated by Django 6.0.4 on 2026-04-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_syllabus_lab_slots_alter_syllabus_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='see_marks',
            field=models.IntegerField(default=0),
        ),
    ]
